name: Deploy Portfolio to IPFS via Pinata

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies & Build
      run: |
        npm ci
        npm run build

    - name: Pin to Pinata (IPFS)
      uses: AquilX/pinata-action@v1.0.1
      with:
        pinata-api-key: ${{ secrets.PINATA_API_KEY }}
        pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}
        pin-name: 'My-Decentralized-Portfolio'
        path: './dist'
